# Generated by Django 4.2.3 on 2023-07-25 20:50

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Freight',
            fields=[
                ('carrier', models.CharField(max_length=100)),
                ('delivery_time', models.IntegerField()),
                ('delivery_cost', models.CharField(max_length=100)),
                ('external_freight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='freight', related_query_name='freight', to='order.order')),
            ],
        ),
    ]
