# Generated by Django 4.2.3 on 2023-07-25 20:50

from django.db import migrations, models
from django.contrib.auth.models import User
import uuid


def create_admin_user(apps, schema_editor):
    User.objects.create_superuser('admin', 'admin@example.com', 'admin')


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.RunPython(create_admin_user),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4,
                 editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('amount', models.FloatField()),
                ('weight', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('length', models.FloatField()),
                ('zip_from', models.CharField(max_length=8)),
                ('zip_to', models.CharField(max_length=8)),
            ],
        ),
    ]
